"""Initial migration: create recipes and cache tables

Revision ID: ad26d224877c
Revises: 
Create Date: 2026-01-06 16:57:51.531636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad26d224877c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_matching_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_ingredient', sa.String(length=255), nullable=False),
    sa.Column('recipe_ingredient', sa.String(length=255), nullable=False),
    sa.Column('match_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('substitution_possible', sa.Boolean(), nullable=True),
    sa.Column('llm_reason', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_matching_recipe_ingredient', 'ingredient_matching_cache', ['recipe_ingredient'], unique=False)
    op.create_index('idx_matching_user_ingredient', 'ingredient_matching_cache', ['user_ingredient'], unique=False)
    op.create_table('recipe_search_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingredient_hash', sa.String(length=64), nullable=False),
    sa.Column('ingredients', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('recipe_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('match_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_hash')
    )
    op.create_index('idx_cache_expires_at', 'recipe_search_cache', ['expires_at'], unique=False)
    op.create_index('idx_cache_ingredient_hash', 'recipe_search_cache', ['ingredient_hash'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cooking_time', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('serving_size', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('nutrition_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('validation_passed', sa.Boolean(), nullable=True),
    sa.Column('nutrition_accuracy', sa.Float(), nullable=True),
    sa.Column('step_completeness', sa.Float(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('select_count', sa.Integer(), nullable=True),
    sa.Column('avg_match_score', sa.Float(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recipes_category', 'recipes', ['category'], unique=False)
    op.create_index('idx_recipes_created_at', 'recipes', ['created_at'], unique=False)
    op.create_index('idx_recipes_difficulty', 'recipes', ['difficulty'], unique=False)
    op.create_index('idx_recipes_quality_score', 'recipes', ['quality_score'], unique=False)
    op.create_index('idx_recipes_source_type', 'recipes', ['source_type'], unique=False)
    op.create_table('user_search_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('ingredients', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('persona', sa.String(length=20), nullable=True),
    sa.Column('selected_recipe_id', sa.UUID(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('search_timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_history_session_id', 'user_search_history', ['session_id'], unique=False)
    op.create_index('idx_history_timestamp', 'user_search_history', ['search_timestamp'], unique=False)
    op.create_index('idx_history_user_id', 'user_search_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_history_user_id', table_name='user_search_history')
    op.drop_index('idx_history_timestamp', table_name='user_search_history')
    op.drop_index('idx_history_session_id', table_name='user_search_history')
    op.drop_table('user_search_history')
    op.drop_index('idx_recipes_source_type', table_name='recipes')
    op.drop_index('idx_recipes_quality_score', table_name='recipes')
    op.drop_index('idx_recipes_difficulty', table_name='recipes')
    op.drop_index('idx_recipes_created_at', table_name='recipes')
    op.drop_index('idx_recipes_category', table_name='recipes')
    op.drop_table('recipes')
    op.drop_index('idx_cache_ingredient_hash', table_name='recipe_search_cache')
    op.drop_index('idx_cache_expires_at', table_name='recipe_search_cache')
    op.drop_table('recipe_search_cache')
    op.drop_index('idx_matching_user_ingredient', table_name='ingredient_matching_cache')
    op.drop_index('idx_matching_recipe_ingredient', table_name='ingredient_matching_cache')
    op.drop_table('ingredient_matching_cache')
    # ### end Alembic commands ###
